# Generated by Django 4.2.17 on 2025-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='converted_mei_file',
            field=models.FileField(blank=True, null=True, upload_to='mei/'),
        ),
    ]
